name: alchemy-test-containers-in-java

on: push

jobs:
  test:
    name: alchemy-test-containers-in-java
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repo
        uses: actions/checkout@v2

      - name: Setup java version
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4

      - name: Run test
        run: |
          mvn -B clean install

